apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: comments
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m
  prune: true
  path: ./apps/comments/prod
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: comments
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches: []
  postBuild:
    substitute:
      ingress_host: comments.example.com
      tls_secret_name: comments.example.com-tls
      middlewares: "kube-system-redirect-scheme@kubernetescrd"