apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./image-policy.yaml
  - ./image-repository.yaml
  - ./image-update-automation.yaml
  
patches:
  - path: pv-patch.yaml
  - path: deployment-patch.yaml

namespace: comments