apiVersion: v1
kind: PersistentVolume
metadata:
  name: valkey-pv
  labels:
    type: nfs
    app: valkey
spec:
  nfs:
    server: 10.0.10.7  # Ihre NFS-Server IP hier eintragen
    path: /srv/nfs/k8s-pv/production/comments-valkey  # Pfad zu existierenden Daten